project:
  type: website
  output-dir: docs

website:
  title: "Nathan Dhanani"
  navbar:
    left:
      - text: "About Me"
        href: about.html
      - text: "DataViz"
        menu: 
          - text: "NFL Salaries"
            href: NFLsalaries.html
          - text: "Fast Food Calorie Count"
            href: FastFood.html

format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

