project:
  type: website
  output-dir: docs

website:
  title: "Nathan Dhanani"
  navbar:
    left:
      - text: "DataViz"
        menu: 
          - text: "NFL Salaries"
            href: NFLsalaries.html
          - text: "Fast Food Calorie Count"
            href: FastFood.html
      - text: "StringAnalysis"
        menu: 
        - text: "NY Times Articles"
          href: Stinganalysis.html
      - text: "Permutation test"
        menu:
          - text: "Financial Institution study" 
            href: permutation_test.html

format:
  html:
    theme: 
      light: minty
      dark: solar
    css: styles.css
    toc: true
    page-layout: full

editor: visual

